openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
paths:
  /api/products:
    post:
      summary: Agregar un nuevo producto a la base de datos(necesitas logear como admin o premium)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                code:
                  type: string
                category:
                  type: string
              example:
                title: Producto de Ejemplo
                description: Descripción del Producto de Ejemplo
                price: 999
                code: P999
                category: Categoría de Ejemplo
      responses:
        "201":
          description: Producto agregado exitosamente
          content:
            application/json:
              example:
                title: Producto de Ejemplo
                description: Descripción del Producto de Ejemplo
                price: 999
                code: P999
                category: Categoría de Ejemplo
        "401":
          description: No autorizado
    get:
      summary: Obtiene la lista de productos de la base de datos (necesitas logear como admin)
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              example:
                - title: Producto 1
                  description: Descripción del Producto 1
                  price: 1000
                  code: P1
                  category: Categoría 1
                - title: Producto 2
                  description: Descripción del Producto 2
                  price: 1500
                  code: P2
                  category: Categoría 2
        "401":
          description: No autorizado

  /api/products/edit/{id}:
    put:
      summary: Edita un producto existente RECOMIENDO usar su correo real para el owner asi al hacer la prueba de eliminación de producto le llega la notificacion de la eliminación (necesitas logear como admin)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto a editar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Nuevo nombre del producto
                price:
                  type: number
                  description: Nuevo precio del producto
                description:
                  type: string
                  description: Nueva descripción del producto
                owner:
                  type: string
                  description: Nuevo owner
      responses:
        "200":
          description: Producto editado exitosamente
          content:
            application/json:
              example:
                message: "Producto editado exitosamente"
        "401":
          description: No autorizado
          content:
            application/json:
              example:
                message: "No estás autorizado para editar este producto"
        "404":
          description: Producto no encontrado
          content:
            application/json:
              example:
                message: "El producto no fue encontrado"

  /api/products/delete/{id}:
    delete:
      summary: Elimina un producto (necesitas logear como admin o premium para eliminar producto propio)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto a eliminar
      responses:
        "204":
          description: Producto eliminado exitosamente
        "401":
          description: No autorizado
        "404":
          description: Producto no encontrado
