openapi: 3.0.0
info:
  title: API de Carritos
  version: 1.0.0
paths:
  /api/cart/{cartId}:
    get:
      summary: Obtiene el contenido de un carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: Respuesta exitosa
        "401":
          description: No autorizado
        "404":
          description: Carrito no encontrado
  /api/cart/create:
    post:
      summary: Crea un carrito para un usuario
      responses:
        "201":
          description: Carrito creado exitosamente
        "401":
          description: No autorizado
  /api/cart/{cartId}/add/{productId}:
    put:
      summary: Agrega un producto al carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto a agregar
      responses:
        "200":
          description: Producto agregado exitosamente
        "401":
          description: No autorizado
        "404":
          description: Carrito o producto no encontrado
  /api/cart/{cartId}/edit/{productId}:
    put:
      summary: Edita un producto en el carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto a editar
      responses:
        "200":
          description: Producto editado exitosamente
        "401":
          description: No autorizado
        "404":
          description: Carrito o producto no encontrado
  /api/cart/{cartId}/purchase:
    post:
      summary: Realiza una compra con el carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: Compra realizada exitosamente
        "401":
          description: No autorizado
        "404":
          description: Carrito no encontrado
  /api/cart/{cartId}/remove/{productId}:
    delete:
      summary: Elimina un producto del carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto a eliminar
      responses:
        "204":
          description: Producto eliminado exitosamente
        "401":
          description: No autorizado
        "404":
          description: Carrito o producto no encontrado
